-- MySQL Script generated by MySQL Workbench
-- qua 18 dez 2019 18:39:32 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD-Trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD-Trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD-Trabalho` DEFAULT CHARACTER SET utf8 ;
USE `BD-Trabalho` ;

-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Morada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Morada` (
  `idMorada` INT NOT NULL,
  `Rua` VARCHAR(100) NOT NULL,
  `CodPostal` VARCHAR(100) NOT NULL,
  `Localidade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMorada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Atleta` (
  `idAtleta` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `dataNascimento` INT NOT NULL,
  `morada` INT NOT NULL,
  `sexo` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idAtleta`),
  INDEX `fk_Atleta_Morada_idx` (`morada` ASC),
  CONSTRAINT `fk_Atleta_Morada`
    FOREIGN KEY (`morada`)
    REFERENCES `BD-Trabalho`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Prova` (
  `idProva` INT NOT NULL,
  `designacao` VARCHAR(100) NOT NULL,
  `modalidade` VARCHAR(100) NOT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`idProva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Atleta_Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Atleta_Prova` (
  `idAtleta_Prova` INT NOT NULL,
  `idProva_Atleta` INT NOT NULL,
  `data` DATE NOT NULL,
  INDEX `fk_Atleta_Prova_Modalidade_prova_idx` (`idProva_Atleta` ASC),
  PRIMARY KEY (`data`, `idProva_Atleta`, `idAtleta_Prova`),
  CONSTRAINT `fk_Atleta_Prova_Modalidade_atleta`
    FOREIGN KEY (`idAtleta_Prova`)
    REFERENCES `BD-Trabalho`.`Atleta` (`idAtleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atleta_Prova_Modalidade_prova`
    FOREIGN KEY (`idProva_Atleta`)
    REFERENCES `BD-Trabalho`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Clinica` (
  `idClinica` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `morada` INT NOT NULL,
  PRIMARY KEY (`idClinica`),
  INDEX `fk_Hospital_Morada_idx` (`morada` ASC),
  CONSTRAINT `fk_Hospital_Morada`
    FOREIGN KEY (`morada`)
    REFERENCES `BD-Trabalho`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Medico` (
  `idMedico` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `idChefe` INT NULL,
  `idHospital` INT NOT NULL,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_Tecnico_Hospital_idx` (`idHospital` ASC),
  INDEX `fk_Medico_Chefe_idx` (`idChefe` ASC),
  CONSTRAINT `fk_Medico_Chefe`
    FOREIGN KEY (`idChefe`)
    REFERENCES `BD-Trabalho`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tecnico_Hospital`
    FOREIGN KEY (`idHospital`)
    REFERENCES `BD-Trabalho`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`TesteClinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`TesteClinico` (
  `idTesteClinico` INT NOT NULL,
  `designacao` VARCHAR(100) NOT NULL,
  `idMedico` INT NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `idAtleta` INT NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `resultado` VARCHAR(100) NULL,
  PRIMARY KEY (`idTesteClinico`),
  INDEX `fk_TesteClinico_Tecnico1_idx` (`idMedico` ASC),
  INDEX `fk_TesteClinico_Atleta_idx` (`idAtleta` ASC),
  CONSTRAINT `fk_TesteClinico_Tecnico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `BD-Trabalho`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TesteClinico_Atleta`
    FOREIGN KEY (`idAtleta`)
    REFERENCES `BD-Trabalho`.`Atleta` (`idAtleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Tecnico_Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Tecnico_Responsavel` (
  `idTecnico_Responsavel` INT NOT NULL,
  `Tecnico_Responsavelcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTecnico_Responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Prova_Teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Prova_Teste` (
  `idProva` INT NOT NULL,
  `designacao` VARCHAR(100) NOT NULL,
  CONSTRAINT `fk_Prova_Teste_Prova`
    FOREIGN KEY (`idProva`)
    REFERENCES `BD-Trabalho`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-Trabalho`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-Trabalho`.`Contacto` (
  `telefone` INT NULL,
  `email` VARCHAR(45) NULL,
  `idContacto` VARCHAR(45) NOT NULL,
  `idAtleta` INT NOT NULL,
  PRIMARY KEY (`idContacto`, `idAtleta`),
  INDEX `fk_Contacto_Atleta1_idx` (`idAtleta` ASC),
  CONSTRAINT `fk_Contacto_Atleta1`
    FOREIGN KEY (`idAtleta`)
    REFERENCES `BD-Trabalho`.`Atleta` (`idAtleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
